# python lsp
[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]

# yaml lsp
[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

# toml lsp
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

# html lsp
[language-server.emmet-language-server]
args = ["--stdio"]
command="emmet-language-server"

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-language-server"]
